### ISSUE TITLE
Hangs on doing sudo

### ISSUE THREAD

**Issue by chabgood** [capistrano-plugins/capistrano-memcached#1]
The capistrano hangs on doing:
/usr/bin/env sudo useradd memcache; true

**Comment by niuage** [comment]
I have the same issue.

If I don't add `set :pty, true` to deploy.rb, then I get: `sudo: no tty present and no askpass program specified`

If I do, then it asks for the password, but then hangs.

**Comment by rhomeister** [comment]
@chabgood does @niuage's workaround help solve your problem?

**Comment by chabgood** [comment]
Thanks, I will let you know if I have any issue in the future.
